[theme]
primaryColor = "#4CAF50"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false 